# /**
#  * @file: docker-compose.yml
#  * @description: Docker Compose для Timeweb App Platform (минимальная конфигурация)
#  * @dependencies: Dockerfile, Caddyfile
#  * @created: 2025-12-05
#  */

services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
